[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:388 DELETE http://127.0.0.1:52900/session/1b505b0d8e503cb9c1e0fbf77d939035 {}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:442 http://127.0.0.1:52900 "DELETE /session/1b505b0d8e503cb9c1e0fbf77d939035 HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:440 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:52900/session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize {}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:271 Resetting dropped connection: 127.0.0.1
[35mDEBUG   [0m urllib3.util.retry:retry.py:441 Incremented Retry for (url='/session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C106727048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (2): 127.0.0.1:52900
[35mDEBUG   [0m urllib3.util.retry:retry.py:441 Incremented Retry for (url='/session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C1071AAFC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (3): 127.0.0.1:52900
[35mDEBUG   [0m urllib3.util.retry:retry.py:441 Incremented Retry for (url='/session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C107096248>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1b505b0d8e503cb9c1e0fbf77d939035/window/maximize
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (4): 127.0.0.1:52900