{
  "uid" : "e46f222eecc919f4",
  "name" : "业务环节经办规则维护模块新增",
  "fullName" : "test_nka03eventrule.TestEventRuleMaintenance#test_EventRuleMaintenance",
  "historyId" : "5dcf5915f86272414c87087883b44b4b",
  "time" : {
    "start" : 1604900005451,
    "stop" : 1604900005451,
    "duration" : 0
  },
  "description" : "业务环节经办规则维护,本次执行时间为：2020-11-09 13:31:48",
  "descriptionHtml" : "<p>业务环节经办规则维护,本次执行时间为：2020-11-09 13:31:48</p>\n",
  "status" : "broken",
  "statusMessage" : "IndexError: list index out of range",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1b505b0d8e503cb9c1e0fbf77d939035\")>\n\n    @pytest.fixture(scope=\"session\")\n    def login(driver):\n        web = LoginPage(driver)\n>       web.login(ini.username, ini.password, ini.verificationCode)\n\nconftest.py:79: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npageobject\\loginpage.py:28: in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pageobject.loginpage.LoginPage object at 0x000001C106743B48>\nlocator = ('name', 'verificationCode'), text = '9527', doc = '登录界面-登录功能'\nindex = 0\n\n    def send_keys(self, locator, text, doc=\"\", index=0):\n        \"\"\"\n        键盘输入操作\n        :param locator: (BY.XPATH, //div)\n        :param text: 输入内容\n        :param doc: 记录日志描述：模块名——页面名——操作名\n        :param index: 结果列表例如(BY.XPATH, //div)[0]\n        :return:\n        \"\"\"\n        try:\n            elements = self.find_elements(*locator, doc=doc)\n>           elements[index].click()  # 点击\nE           IndexError: list index out of range\n\npageobject\\basepage.py:220: IndexError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1604899908928,
      "stop" : 1604899912319,
      "duration" : 3391
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604899912319,
      "stop" : 1604899968254,
      "duration" : 55935
    },
    "status" : "broken",
    "statusMessage" : "IndexError: list index out of range\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604899912321,
        "stop" : 1604899968253,
        "duration" : 55932
      },
      "status" : "broken",
      "statusMessage" : "IndexError: list index out of range\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604899968358,
      "stop" : 1604900001608,
      "duration" : 33250
    },
    "status" : "broken",
    "statusMessage" : "IndexError: list index out of range\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604899968362,
        "stop" : 1604900001608,
        "duration" : 33246
      },
      "status" : "broken",
      "statusMessage" : "IndexError: list index out of range\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900001690,
      "stop" : 1604900005407,
      "duration" : 3717
    },
    "status" : "broken",
    "statusMessage" : "IndexError: list index out of range\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900001694,
        "stop" : 1604900005407,
        "duration" : 3713
      },
      "status" : "broken",
      "statusMessage" : "IndexError: list index out of range\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 28, in login\n    self.send_keys(loc.input_verificationCode, verificationCode, doc=doc)  # 输入验证码，不用就注掉\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\basepage.py\", line 220, in send_keys\n    elements[index].click()  # 点击\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900005567,
      "stop" : 1604900005577,
      "duration" : 10
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900005572,
        "stop" : 1604900005576,
        "duration" : 4
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900005719,
      "stop" : 1604900005728,
      "duration" : 9
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900005723,
        "stop" : 1604900005727,
        "duration" : 4
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900005849,
      "stop" : 1604900005855,
      "duration" : 6
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900005852,
        "stop" : 1604900005855,
        "duration" : 3
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900005952,
      "stop" : 1604900005959,
      "duration" : 7
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900005955,
        "stop" : 1604900005958,
        "duration" : 3
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006052,
      "stop" : 1604900006058,
      "duration" : 6
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006054,
        "stop" : 1604900006057,
        "duration" : 3
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006142,
      "stop" : 1604900006147,
      "duration" : 5
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006144,
        "stop" : 1604900006146,
        "duration" : 2
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006229,
      "stop" : 1604900006234,
      "duration" : 5
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006232,
        "stop" : 1604900006234,
        "duration" : 2
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006313,
      "stop" : 1604900006318,
      "duration" : 5
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006316,
        "stop" : 1604900006318,
        "duration" : 2
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006400,
      "stop" : 1604900006406,
      "duration" : 6
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006402,
        "stop" : 1604900006405,
        "duration" : 3
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006501,
      "stop" : 1604900006507,
      "duration" : 6
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006504,
        "stop" : 1604900006506,
        "duration" : 2
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1604900006587,
      "stop" : 1604900006592,
      "duration" : 5
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
    "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\conftest.py\", line 79, in login\n    web.login(ini.username, ini.password, ini.verificationCode)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "登录",
      "time" : {
        "start" : 1604900006589,
        "stop" : 1604900006592,
        "duration" : 3
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.183)\n\n",
      "statusTrace" : "  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\cspytest\\pageobject\\loginpage.py\", line 22, in login\n    self.driver.get(ini.url)  # 调用浏览器打开测试地址\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\administrator\\pycharmprojects\\cspytest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'hnadmin'"
      }, {
        "name" : "password",
        "value" : "'1qaz!QAZ'"
      }, {
        "name" : "verificationCode",
        "value" : "'9527'"
      } ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1604900006672,
      "stop" : 1604900008790,
      "duration" : 2118
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "业务环节经办规则维护"
  }, {
    "name" : "feature",
    "value" : "业务环节经办规则维护模块"
  }, {
    "name" : "tag",
    "value" : "nkywgf(reruns=2, reruns_delay=2)"
  }, {
    "name" : "suite",
    "value" : "test_nka03eventrule"
  }, {
    "name" : "subSuite",
    "value" : "TestEventRuleMaintenance"
  }, {
    "name" : "host",
    "value" : "P201903242051"
  }, {
    "name" : "thread",
    "value" : "79224-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_nka03eventrule"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "chkrulename",
    "value" : "'SERVMAT1604899908'"
  }, {
    "name" : "chkrulenode",
    "value" : "'经办规则说明'"
  }, {
    "name" : "mattname",
    "value" : "'SERVMAT1604899908'"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "nkywgf(reruns=2, reruns_delay=2)" ]
  },
  "source" : "e46f222eecc919f4.json",
  "parameterValues" : [ "'SERVMAT1604899908'", "'经办规则说明'", "'SERVMAT1604899908'" ]
}